// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeK1HWzOB14JO9_FILnGsR83m7nmlS3VU',
    appId: '1:799232426817:web:05af9dd453a9f227ac17c0',
    messagingSenderId: '799232426817',
    projectId: 'aman-sellerside-sa',
    authDomain: 'aman-sellerside-sa.firebaseapp.com',
    storageBucket: 'aman-sellerside-sa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoTWKe1gESun6ykvwuaLyoL2ovQaVOQvc',
    appId: '1:799232426817:android:61d4b6b55b9b7848ac17c0',
    messagingSenderId: '799232426817',
    projectId: 'aman-sellerside-sa',
    storageBucket: 'aman-sellerside-sa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxYXng_mUuf905uTffdHLy9rAMe4HWtEI',
    appId: '1:799232426817:ios:ef839e1c8a4b09f2ac17c0',
    messagingSenderId: '799232426817',
    projectId: 'aman-sellerside-sa',
    storageBucket: 'aman-sellerside-sa.appspot.com',
    androidClientId: '799232426817-o4na2sd1mcuo4fa0ad0knnkukfn5l9nu.apps.googleusercontent.com',
    iosClientId: '799232426817-5kc50k3ootvv9s7228c3mbc5rdaoi005.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxYXng_mUuf905uTffdHLy9rAMe4HWtEI',
    appId: '1:799232426817:ios:ef839e1c8a4b09f2ac17c0',
    messagingSenderId: '799232426817',
    projectId: 'aman-sellerside-sa',
    storageBucket: 'aman-sellerside-sa.appspot.com',
    androidClientId: '799232426817-o4na2sd1mcuo4fa0ad0knnkukfn5l9nu.apps.googleusercontent.com',
    iosClientId: '799232426817-5kc50k3ootvv9s7228c3mbc5rdaoi005.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmily',
  );
}
